context = {}

context["HPPULLDOWN"] = "UA - Homepage"
context["HPPULLDOWN2"] = "UA - Homepage"
context["HPPULLDOWN3"] = "UA - Homepage"
context["HPPULLDOWN4"] = "UA - Homepage"
context["SITEMAP"] = "UA - Homepage"

context["MILIEU"]           = "UA - Diensten"
context["ADMINGIDS"]        = "UA - Diensten"
context["INNOVATOX"]        = "UA - Diensten"
context["ROUTE"]            = "UA - Diensten"
context["CONTACT"]          = "UA - Diensten"
context["ROUTEDESCRIPTION"] = "UA - Diensten"

context["FINDIENST"] = "UA - Diensten - Financien"
context["KASDIENST"] = "UA - Diensten - Financien"

context["BB"] = "UA - Diensten - ICT"
context["DELTA"] = "UA - Diensten - ICT"
context["DEPICT"] = "UA - Diensten - ICT"
context["DEPICTIOC"] = "UA - Diensten - ICT"
context["PSOFT"] = "UA - Diensten - ICT"
context["SYS"] = "UA - Diensten - ICT"
context["HELP"] = "UA - Diensten - ICT"
context["STUDADM"] = "UA - Diensten - ICT"
context["ICNMD"] = "UA - Diensten - ICT"
context["WERKGROEPDELTA"] = "UA - Diensten - ICT"
context["SGPEOPLESOFT"] = "UA - Diensten - ICT"
context["SGONDERZOEKSDB"] = "UA - Diensten - ICT"
context["SGSISA"] = "UA - Diensten - ICT"
context["HPNEW8"] = "UA - Diensten - ICT"
context["DEPICT2"] = "UA - Diensten - ICT"
context["SISA"] = "UA - Diensten - ICT"
context["WEBSWOT"] = "UA - Diensten - ICT"
context["INFOCENTER"] = "UA - Diensten - ICT"
context["SYSTEMEN"] = "UA - Diensten - ICT"
context["UANET"] = "UA - Diensten - ICT"
context["HELPDESK"] = "UA - Diensten - ICT"
context["ACADOND"] = "UA - Diensten - ICT"
context["CELENDIENSTHOOFDEN"] = "UA - Diensten - ICT"
context["COMMUNICATIEPLANICT"] = "UA - Diensten - ICT"
context["BBMANUAL"] = "UA - Diensten - ICT"
context["EDUROAM"] = "UA - Diensten - ICT"
context["INFOCENTERSTUDENT"] = "UA - Diensten - ICT"
context["INFOCENTERPERSONEEL"] = "UA - Diensten - ICT"
context["INFOCENTER2"] = "UA - Diensten - ICT"
context["ICT"] = "UA - Diensten - ICT"


context["CDE"] = "UA - Diensten - Infrastructuur"
context["LOKAALRESERVATIE"] = "UA - Diensten - Infrastructuur"
context["TESTAERTS"] = "UA - Diensten - Infrastructuur"
context["REIZEN"] = "UA - Diensten - Infrastructuur"

context["ONW"] = "UA - Diensten - Onderwijs"
context["_OND"] = "UA - Diensten - Onderwijs"
context["STUDPORT"] = "UA - Diensten - Onderwijs"
context["VAKBES"] = "UA - Diensten - Onderwijs"
context["VAKBES2005"] = "UA - Diensten - Onderwijs"
context["OOD2006"] = "UA - Diensten - Onderwijs"
context["OOD2007"] = "UA - Diensten - Onderwijs"
context["OOD2008"] = "UA - Diensten - Onderwijs"
context["OOD2009"] = "UA - Diensten - Onderwijs"
context["INSCHR2009"] = "UA - Diensten - Onderwijs"
context["VOORINSCHRIJVING"] = "UA - Diensten - Onderwijs"
context["VAKBESE"] = "UA - Diensten - Onderwijs"
context["VAKBESE2005"] = "UA - Diensten - Onderwijs"
context["OODE2008"] = "UA - Diensten - Onderwijs"
context["OODE2006"] = "UA - Diensten - Onderwijs"
context["OODE2009"] = "UA - Diensten - Onderwijs"
context["INSCHR2009E"] = "UA - Diensten - Onderwijs"
context["HERINSCHR"] = "UA - Diensten - Onderwijs"
context["ONWBEL"] = "UA - Diensten - Onderwijs"
context["OPENUNIV"] = "UA - Diensten - Onderwijs"
context["STUDENT"] = "UA - Diensten - Onderwijs"
context["INSCHR"] = "UA - Diensten - Onderwijs"
context["RES"] = "UA - Diensten - Onderwijs"
context["STUDPORT2"] = "UA - Diensten - Onderwijs"
context["VOORINSCHR"] = "UA - Diensten - Onderwijs"
context["HERINSCHR2009E"] = "UA - Diensten - Onderwijs"
context["INSCHR2010E"] = "UA - Diensten - Onderwijs"
context["HERINSCHR2010"] = "UA - Diensten - Onderwijs"
context["HERINSCHR2010E"] = "UA - Diensten - Onderwijs"
context["OOD2010"] = "UA - Diensten - Onderwijs"
context["OODE2010"] = "UA - Diensten - Onderwijs"
context["Inhoud"] = "UA - Diensten - Onderwijs"


context["INTERF"] = "UA - Diensten - Onderzoek"
context["RESTOP"] = "UA - Diensten - Onderzoek"
context["ZAPBOF"] = "UA - Diensten - Onderzoek"
context["BWS06"] = "UA - Diensten - Onderzoek"
context["IOF2005"] = "UA - Diensten - Onderzoek"
context["TOPBOF"] = "UA - Diensten - Onderzoek"
context["NOI2003"] = "UA - Diensten - Onderzoek"
context["CHROZ"] = "UA - Diensten - Onderzoek"
context["CAPRI"] = "UA - Diensten - Onderzoek"
context["TONYRESARCH"] = "UA - Diensten - Onderzoek"
context["METHUSALEM"] = "UA - Diensten - Onderzoek"
context["TOP20102013"] = "UA - Diensten - Onderzoek"
context["RESEARCHEVALPHYSICS"] = "UA - Diensten - Onderzoek"
context["ONDERZK2"] = "UA - Diensten - Onderzoek"

context["FUFL"] = "UA - Diensten - Personeel"
context["PERSDIENS"] = "UA - Diensten - Personeel"
context["PERSINFO"] = "UA - Diensten - Personeel"
context["PERSINFOPERSINFO"] = "UA - Diensten - Personeel"
context["PERSPORT"] = "UA - Diensten - Personeel"
context["PROCBOEK"] = "UA - Diensten - Personeel"
context["VACATURES"] = "UA - Diensten - Personeel"
context["PERSONEEL"] = "UA - Diensten - Personeel"
context["DIENSTH"] = "UA - Diensten - Personeel"
context["VABAP"] = "UA - Diensten - Personeel"
context["DEPTPERSONEEL"] = "UA - Diensten - Personeel"
context["PERSONEEL2"] = "UA - Diensten - Personeel"
context["PERSONEELSVERENIGING"] = "UA - Diensten - Personeel"





