context = {}

context["HPPULLDOWN"] = "UA - Homepage"
context["HPPULLDOWN2"] = "UA - Homepage"
context["HPPULLDOWN3"] = "UA - Homepage"
context["HPPULLDOWN4"] = "UA - Homepage"
context["SITEMAP"] = "UA - Homepage"

context["MILIEU"]           = "UA - Diensten"
context["ADMINGIDS"]        = "UA - Diensten"
context["INNOVATOX"]        = "UA - Diensten"
context["ROUTE"]            = "UA - Diensten"
context["CONTACT"]          = "UA - Diensten"
context["ROUTEDESCRIPTION"] = "UA - Diensten"

context["FINDIENST"] = "UA - Diensten - Financien"
context["KASDIENST"] = "UA - Diensten - Financien"

context["BB"] = "UA - Diensten - ICT"
context["DELTA"] = "UA - Diensten - ICT"
context["DEPICT"] = "UA - Diensten - ICT"
context["DEPICTIOC"] = "UA - Diensten - ICT"
context["PSOFT"] = "UA - Diensten - ICT"
context["SYS"] = "UA - Diensten - ICT"
context["HELP"] = "UA - Diensten - ICT"
context["STUDADM"] = "UA - Diensten - ICT"
context["ICNMD"] = "UA - Diensten - ICT"
context["WERKGROEPDELTA"] = "UA - Diensten - ICT"
context["SGPEOPLESOFT"] = "UA - Diensten - ICT"
context["SGONDERZOEKSDB"] = "UA - Diensten - ICT"
context["SGSISA"] = "UA - Diensten - ICT"
context["HPNEW8"] = "UA - Diensten - ICT"
context["DEPICT2"] = "UA - Diensten - ICT"
context["SISA"] = "UA - Diensten - ICT"
context["WEBSWOT"] = "UA - Diensten - ICT"
context["INFOCENTER"] = "UA - Diensten - ICT"
context["SYSTEMEN"] = "UA - Diensten - ICT"
context["UANET"] = "UA - Diensten - ICT"
context["HELPDESK"] = "UA - Diensten - ICT"
context["ACADOND"] = "UA - Diensten - ICT"
context["CELENDIENSTHOOFDEN"] = "UA - Diensten - ICT"
context["COMMUNICATIEPLANICT"] = "UA - Diensten - ICT"
context["BBMANUAL"] = "UA - Diensten - ICT"
context["EDUROAM"] = "UA - Diensten - ICT"
context["INFOCENTERSTUDENT"] = "UA - Diensten - ICT"
context["INFOCENTERPERSONEEL"] = "UA - Diensten - ICT"
context["INFOCENTER2"] = "UA - Diensten - ICT"
context["ICT"] = "UA - Diensten - ICT"


context["CDE"] = "UA - Diensten - Infrastructuur"
context["LOKAALRESERVATIE"] = "UA - Diensten - Infrastructuur"
context["TESTAERTS"] = "UA - Diensten - Infrastructuur"
context["REIZEN"] = "UA - Diensten - Infrastructuur"

context["ONW"] = "UA - Diensten - Onderwijs"
context["_OND"] = "UA - Diensten - Onderwijs"
context["STUDPORT"] = "UA - Diensten - Onderwijs"
context["VAKBES"] = "UA - Diensten - Onderwijs"
context["VAKBES2005"] = "UA - Diensten - Onderwijs"
context["OOD2006"] = "UA - Diensten - Onderwijs"
context["OOD2007"] = "UA - Diensten - Onderwijs"
context["OOD2008"] = "UA - Diensten - Onderwijs"
context["OOD2009"] = "UA - Diensten - Onderwijs"
context["INSCHR2009"] = "UA - Diensten - Onderwijs"
context["VOORINSCHRIJVING"] = "UA - Diensten - Onderwijs"
context["VAKBESE"] = "UA - Diensten - Onderwijs"
context["VAKBESE2005"] = "UA - Diensten - Onderwijs"
context["OODE2008"] = "UA - Diensten - Onderwijs"
context["OODE2006"] = "UA - Diensten - Onderwijs"
context["OODE2009"] = "UA - Diensten - Onderwijs"
context["INSCHR2009E"] = "UA - Diensten - Onderwijs"
context["HERINSCHR"] = "UA - Diensten - Onderwijs"
context["ONWBEL"] = "UA - Diensten - Onderwijs"
context["OPENUNIV"] = "UA - Diensten - Onderwijs"
context["STUDENT"] = "UA - Diensten - Onderwijs"
context["INSCHR"] = "UA - Diensten - Onderwijs"
context["RES"] = "UA - Diensten - Onderwijs"
context["STUDPORT2"] = "UA - Diensten - Onderwijs"
context["VOORINSCHR"] = "UA - Diensten - Onderwijs"
context["HERINSCHR2009E"] = "UA - Diensten - Onderwijs"
context["INSCHR2010E"] = "UA - Diensten - Onderwijs"
context["HERINSCHR2010"] = "UA - Diensten - Onderwijs"
context["HERINSCHR2010E"] = "UA - Diensten - Onderwijs"
context["OOD2010"] = "UA - Diensten - Onderwijs"
context["OODE2010"] = "UA - Diensten - Onderwijs"
context["Inhoud"] = "UA - Diensten - Onderwijs"


context["INTERF"] = "UA - Diensten - Onderzoek"
context["RESTOP"] = "UA - Diensten - Onderzoek"
context["ZAPBOF"] = "UA - Diensten - Onderzoek"
context["BWS06"] = "UA - Diensten - Onderzoek"
context["IOF2005"] = "UA - Diensten - Onderzoek"
context["TOPBOF"] = "UA - Diensten - Onderzoek"
context["NOI2003"] = "UA - Diensten - Onderzoek"
context["CHROZ"] = "UA - Diensten - Onderzoek"
context["CAPRI"] = "UA - Diensten - Onderzoek"
context["TONYRESARCH"] = "UA - Diensten - Onderzoek"
context["METHUSALEM"] = "UA - Diensten - Onderzoek"
context["TOP20102013"] = "UA - Diensten - Onderzoek"
context["RESEARCHEVALPHYSICS"] = "UA - Diensten - Onderzoek"
context["ONDERZK2"] = "UA - Diensten - Onderzoek"

context["FUFL"] = "UA - Diensten - Personeel"
context["PERSDIENS"] = "UA - Diensten - Personeel"
context["PERSINFO"] = "UA - Diensten - Personeel"
context["PERSINFOPERSINFO"] = "UA - Diensten - Personeel"
context["PERSPORT"] = "UA - Diensten - Personeel"
context["PROCBOEK"] = "UA - Diensten - Personeel"
context["VACATURES"] = "UA - Diensten - Personeel"
context["PERSONEEL"] = "UA - Diensten - Personeel"
context["DIENSTH"] = "UA - Diensten - Personeel"
context["VABAP"] = "UA - Diensten - Personeel"
context["DEPTPERSONEEL"] = "UA - Diensten - Personeel"
context["PERSONEEL2"] = "UA - Diensten - Personeel"
context["PERSONEELSVERENIGING"] = "UA - Diensten - Personeel"

context["KOK"] = "UA - Diensten - Stafdiensten Rector"
context["brantijser"] = "UA - Diensten - Stafdiensten Rector"

context["PAVO"] = "UA - Diensten - Wmd."
context["WMDRAAD"] = "UA - Diensten - Wmd."
context["WETCOM"] = "UA - Diensten - Wmd."
context["GELIJKEKANSEN"] = "UA - Diensten - Wmd."
context["DOTONTW"] = "UA - Diensten - Wmd."
context["SGMVO"] = "UA - Diensten - Wmd."
context["DUURONT"] = "UA - Diensten - Wmd."
context["MVOND"] = "UA - Diensten - Wmd."
context["KLIMAATWEEK"] = "UA - Diensten - Wmd."


context["VAOPAVO"] = "UA - Diensten - Studentgerichte diensten"
context["ADSTUD"] = "UA - Diensten - Studentgerichte diensten"
context["DIS"] = "UA - Diensten - Studentgerichte diensten"
context["VAOPAVO"] = "UA - Diensten - Studentgerichte diensten"
context["contactpersonenslb"] = "UA - Diensten - Studentgerichte diensten"
context["STUDENTENRAAD"] = "UA - Diensten - Studentgerichte diensten"
context["EITEI"] = "UA - Diensten - Studentgerichte diensten"
context["MASTERS"] = "UA - Diensten - Studentgerichte diensten"
context["ONTHAALDAG"] = "UA - Diensten - Studentgerichte diensten"
context["SEPTEMBER"] = "UA - Diensten - Studentgerichte diensten"
context["ECV"] = "UA - Diensten - Studentgerichte diensten"
context["DSSBTRAININGEN"] = "UA - Diensten - Studentgerichte diensten"
context["NDLANTWERPEN"] = "UA - Diensten - Studentgerichte diensten"
context["CULTUURAANUA"] = "UA - Diensten - Studentgerichte diensten"
context["SOULINABOWL"] = "UA - Diensten - Studentgerichte diensten"
context["OPENLESDAGEN"] = "UA - Diensten - Studentgerichte diensten"
context["STUDIELOOPBAANBEGELEIDING"] = "UA - Diensten - Studentgerichte diensten"
context["ECEI"] = "UA - Diensten - Studentgerichte diensten"
context["LEERONSKENNEN"] = "UA - Diensten - Studentgerichte diensten"
context["STUDENTENCLUBS"] = "UA - Diensten - Studentgerichte diensten"

context["VERZEKER"] = "UA - Diensten - Verzekeringen"

context["PBW"] = "UA - Diensten - PBW"

context["IDKIJK"] = "UA - Diensten - Dep Communicatie"
context["INTRAM"] = "UA - Diensten - Dep Communicatie"
context["NEWS"] = "UA - Diensten - Dep Communicatie"
context["EREDOC"] = "UA - Diensten - Dep Communicatie"
context["HUISSTIJL"] = "UA - Diensten - Dep Communicatie"
context["EREDOC2006"] = "UA - Diensten - Dep Communicatie"
context["KINDERUNIVERSITEIT"] = "UA - Diensten - Dep Communicatie"
context["PLAATSING"] = "UA - Diensten - Dep Communicatie"
context["GVASTATS"] = "UA - Diensten - Dep Communicatie"
context["COMMUNICATIE"] = "UA - Diensten - Dep Communicatie"
context["INSCHRPERSFEEST"] = "UA - Diensten - Dep Communicatie"

context["BESTCOL"] = "UA - Diensten - Bestuurlijk"
context["COLBEHEER"] = "UA - Diensten - Bestuurlijk"
context["CVD"] = "UA - Diensten - Bestuurlijk"
context["HOGERAAD"] = "UA - Diensten - Bestuurlijk"
context["HUISHREGL"] = "UA - Diensten - Bestuurlijk"
context["ORGANOGRA"] = "UA - Diensten - Bestuurlijk"
context["REGLEM"] = "UA - Diensten - Bestuurlijk"
context["RVB"] = "UA - Diensten - Bestuurlijk"
context["VERGADER"] = "UA - Diensten - Bestuurlijk"
context["AUDIT"] = "UA - Diensten - Bestuurlijk"
context["BESTUUR"] = "UA - Diensten - Bestuurlijk"
context["COBAD"] = "UA - Diensten - Bestuurlijk"
context["INTERNBELEID"] = "UA - Diensten - Bestuurlijk"

context["PASDIENST"] = "Diensten - Levensbeschouwelijk"
context["USAB"] = "Diensten - Levensbeschouwelijk"
context["VERKENNINGSDAGEN"] = "Diensten - Levensbeschouwelijk"
context["VERKENNINGSDAGENCMI"] = "Diensten - Levensbeschouwelijk"
context["VERKENNINGSDAGENCST"] = "Diensten - Levensbeschouwelijk"
context["ZOMERSCHOOL"] = "Diensten - Levensbeschouwelijk"
context["LUSTENZONDE"] = "Diensten - Levensbeschouwelijk"
context["VRIJZINNIG"] = "Diensten - Levensbeschouwelijk"
context["OVERLIJDEN"] = "Diensten - Levensbeschouwelijk"


context["EAIE"] = "UA - Diensten - Internationaal"
context["DISTESTNL"] = "UA - Diensten - Internationaal"
context["DISTESTE"] = "UA - Diensten - Internationaal"
context["BUDDY"] = "UA - Diensten - Internationaal"
context["PARTNERINFO"] = "UA - Diensten - Internationaal"
context["EAIE08"] = "UA - Diensten - Internationaal"
context["ECTS"] = "UA - Diensten - Internationaal"
context["ASU"] = "UA - Diensten - Internationaal"
context["MIJNVERHAAL"] = "UA - Diensten - Internationaal"
context["PRACTICALGUIDE"] = "UA - Diensten - Internationaal"
context["PROMOB"] = "UA - Diensten - Internationaal"
context["EMCHINA"] = "UA - Diensten - Internationaal"
context["EADIC"] = "UA - Diensten - Internationaal"
context["EMUA"] = "UA - Diensten - Internationaal"
context["EMUNDUS20"] = "UA - Diensten - Internationaal"


context["CBO"] = "UA - Centra en instituten"
context["CENINS"] = "UA - Centra en instituten"
context["CIMDA"] = "UA - Centra en instituten"
context["CMS"] = "UA - Centra en instituten"
context["CMSENG"] = "UA - Centra en instituten"
context["CMSESP"] = "UA - Centra en instituten"
context["CVA"] = "UA - Centra en instituten"
context["CVBB"] = "UA - Centra en instituten"
context["IJS"] = "UA - Centra en instituten"
context["ISLN"] = "UA - Centra en instituten"
context["MILKND"] = "UA - Centra en instituten"
context["PIETERGIL"] = "UA - Centra en instituten"
context["TESTCENTR"] = "UA - Centra en instituten"
context["UATALIN"] = "UA - Centra en instituten"
context["ICTLENG"] = "UA - Centra en instituten"
context["ICTLFR"] = "UA - Centra en instituten"
context["ICTLNL"] = "UA - Centra en instituten"
context["STATUA"] = "UA - Centra en instituten"
context["IJSENG"] = "UA - Centra en instituten"
context["ISUA"] = "UA - Centra en instituten"
context["INDIASC"] = "UA - Centra en instituten"
context["MOBILITY"] = "UA - Centra en instituten"
context["STEM"] = "UA - Centra en instituten"
context["SPIRE"] = "UA - Centra en instituten"
context["EIMTL"] = "UA - Centra en instituten"
context["CEMIS"] = "UA - Centra en instituten"
context["LINGUAPOLISFR"] = "UA - Centra en instituten"
context["LINGUAPOLISEN"] = "UA - Centra en instituten"
context["TOGA"] = "UA - Centra en instituten"
context["ICOR"] = "UA - Centra en instituten"
context["ELA"] = "UA - Centra en instituten"
context["TAALLEERDER"] = "UA - Centra en instituten"
context["MIDP"] = "UA - Centra en instituten"
context["LCV"] = "UA - Centra en instituten"
context["VAXINFECTIO"] = "UA - Centra en instituten"
context["CALL2008"] = "UA - Centra en instituten"
context["CAS"] = "UA - Centra en instituten"
context["MONITORAAT"] = "UA - Centra en instituten"
context["LINGUAPOLIS_OPENDEUR"] = "UA - Centra en instituten"
context["ISC"] = "UA - Centra en instituten"
context["SEPIA"] = "UA - Centra en instituten"
context["LINGUANLPART"] = "UA - Centra en instituten"
context["LINGUANLBEDR"] = "UA - Centra en instituten"
context["LINGUANLOO"] = "UA - Centra en instituten"
context["LINGUANLAC"] = "UA - Centra en instituten"
context["LINGUANLANDERE"] = "UA - Centra en instituten"
context["LINGUANL"] = "UA - Centra en instituten"
context["CALL2010"] = "UA - Centra en instituten"
context["LINGUANLEXTRA"] = "UA - Centra en instituten"
context["ESM"] = "UA - Centra en instituten"
context["SBO"] = "UA - Centra en instituten"
context["LINGUASUMMERSCHOOL"] = "UA - Centra en instituten"
context["SHAREPROJECT"] = "UA - Centra en instituten"
context["MIGRATIEHERINNEREN"] = "UA - Centra en instituten"
context["LINGUAFR"] = "UA - Centra en instituten"
context["LINGUAEN"] = "UA - Centra en instituten"
context["LINGUAFREXTRA"] = "UA - Centra en instituten"
context["LINGUAENEXTRA"] = "UA - Centra en instituten"
context["LINGUAFRANDERE"] = "UA - Centra en instituten"
context["LINGUAENANDERE"] = "UA - Centra en instituten"
context["LINGUAFRAC"] = "UA - Centra en instituten"
context["LINGUAENAC"] = "UA - Centra en instituten"
context["LINGUAFROO"] = "UA - Centra en instituten"
context["LINGUAENOO"] = "UA - Centra en instituten"
context["LINGUAFRBEDR"] = "UA - Centra en instituten"
context["LINGUAENBEDR"] = "UA - Centra en instituten"
context["LINGUAFRPART"] = "UA - Centra en instituten"
context["LINGUAENPART"] = "UA - Centra en instituten"
context["ENQUETEOCMW"] = "UA - Centra en instituten"
context["WATERTECHNOLOGY"] = "UA - Centra en instituten"
context["IMAMS"] = "UA - Centra en instituten"
context["DEUTSCHCAFE"] = "UA - Centra en instituten"
context["VADEMECUM"] = "UA - Centra en instituten"
context["CZT"] = "UA - Centra en instituten"
context["ORGSYNTH"] = "UA - Centra en instituten"
context["CEMISNL"] = "UA - Centra en instituten"
context["GRUNDTVIG"] = "UA - Centra en instituten"
context["IMAMSE"] = "UA - Centra en instituten"
context["IMAMSF"] = "UA - Centra en instituten"
context["IMAMSA"] = "UA - Centra en instituten"
context["CEMISUK"] = "UA - Centra en instituten"
context["OPRIT14"] = "UA - Centra en instituten"
context["ELSIN"] = "UA - Centra en instituten"













