context = {}

context["HPPULLDOWN"] = "UA - Homepage"
context["HPPULLDOWN2"] = "UA - Homepage"
context["HPPULLDOWN3"] = "UA - Homepage"
context["HPPULLDOWN4"] = "UA - Homepage"
context["SITEMAP"] = "UA - Homepage"

context["MILIEU"]           = "UA - Diensten"
context["ADMINGIDS"]        = "UA - Diensten"
context["INNOVATOX"]        = "UA - Diensten"
context["ROUTE"]            = "UA - Diensten"
context["CONTACT"]          = "UA - Diensten"
context["ROUTEDESCRIPTION"] = "UA - Diensten"

context["FINDIENST"] = "UA - Diensten - Financien"
context["KASDIENST"] = "UA - Diensten - Financien"

context["BB"] = "UA - Diensten - ICT"
context["DELTA"] = "UA - Diensten - ICT"
context["DEPICT"] = "UA - Diensten - ICT"
context["DEPICTIOC"] = "UA - Diensten - ICT"
context["PSOFT"] = "UA - Diensten - ICT"
context["SYS"] = "UA - Diensten - ICT"
context["HELP"] = "UA - Diensten - ICT"
context["STUDADM"] = "UA - Diensten - ICT"
context["ICNMD"] = "UA - Diensten - ICT"
context["WERKGROEPDELTA"] = "UA - Diensten - ICT"
context["SGPEOPLESOFT"] = "UA - Diensten - ICT"
context["SGONDERZOEKSDB"] = "UA - Diensten - ICT"
context["SGSISA"] = "UA - Diensten - ICT"
context["HPNEW8"] = "UA - Diensten - ICT"
context["DEPICT2"] = "UA - Diensten - ICT"
context["SISA"] = "UA - Diensten - ICT"
context["WEBSWOT"] = "UA - Diensten - ICT"
context["INFOCENTER"] = "UA - Diensten - ICT"
context["SYSTEMEN"] = "UA - Diensten - ICT"
context["UANET"] = "UA - Diensten - ICT"
context["HELPDESK"] = "UA - Diensten - ICT"
context["ACADOND"] = "UA - Diensten - ICT"
context["CELENDIENSTHOOFDEN"] = "UA - Diensten - ICT"
context["COMMUNICATIEPLANICT"] = "UA - Diensten - ICT"
context["BBMANUAL"] = "UA - Diensten - ICT"
context["EDUROAM"] = "UA - Diensten - ICT"
context["INFOCENTERSTUDENT"] = "UA - Diensten - ICT"
context["INFOCENTERPERSONEEL"] = "UA - Diensten - ICT"
context["INFOCENTER2"] = "UA - Diensten - ICT"
context["ICT"] = "UA - Diensten - ICT"


context["CDE"] = "UA - Diensten - Infrastructuur"
context["LOKAALRESERVATIE"] = "UA - Diensten - Infrastructuur"
context["TESTAERTS"] = "UA - Diensten - Infrastructuur"
context["REIZEN"] = "UA - Diensten - Infrastructuur"

context["ONW"] = "UA - Diensten - Onderwijs"
context["_OND"] = "UA - Diensten - Onderwijs"
context["STUDPORT"] = "UA - Diensten - Onderwijs"
context["VAKBES"] = "UA - Diensten - Onderwijs"
context["VAKBES2005"] = "UA - Diensten - Onderwijs"
context["OOD2006"] = "UA - Diensten - Onderwijs"
context["OOD2007"] = "UA - Diensten - Onderwijs"
context["OOD2008"] = "UA - Diensten - Onderwijs"
context["OOD2009"] = "UA - Diensten - Onderwijs"
context["INSCHR2009"] = "UA - Diensten - Onderwijs"
context["VOORINSCHRIJVING"] = "UA - Diensten - Onderwijs"
context["VAKBESE"] = "UA - Diensten - Onderwijs"
context["VAKBESE2005"] = "UA - Diensten - Onderwijs"
context["OODE2008"] = "UA - Diensten - Onderwijs"
context["OODE2006"] = "UA - Diensten - Onderwijs"
context["OODE2009"] = "UA - Diensten - Onderwijs"
context["INSCHR2009E"] = "UA - Diensten - Onderwijs"
context["HERINSCHR"] = "UA - Diensten - Onderwijs"
context["ONWBEL"] = "UA - Diensten - Onderwijs"
context["OPENUNIV"] = "UA - Diensten - Onderwijs"
context["STUDENT"] = "UA - Diensten - Onderwijs"
context["INSCHR"] = "UA - Diensten - Onderwijs"
context["RES"] = "UA - Diensten - Onderwijs"
context["STUDPORT2"] = "UA - Diensten - Onderwijs"
context["VOORINSCHR"] = "UA - Diensten - Onderwijs"
context["HERINSCHR2009E"] = "UA - Diensten - Onderwijs"
context["INSCHR2010E"] = "UA - Diensten - Onderwijs"
context["HERINSCHR2010"] = "UA - Diensten - Onderwijs"
context["HERINSCHR2010E"] = "UA - Diensten - Onderwijs"
context["OOD2010"] = "UA - Diensten - Onderwijs"
context["OODE2010"] = "UA - Diensten - Onderwijs"
context["Inhoud"] = "UA - Diensten - Onderwijs"


context["INTERF"] = "UA - Diensten - Onderzoek"
context["RESTOP"] = "UA - Diensten - Onderzoek"
context["ZAPBOF"] = "UA - Diensten - Onderzoek"
context["BWS06"] = "UA - Diensten - Onderzoek"
context["IOF2005"] = "UA - Diensten - Onderzoek"
context["TOPBOF"] = "UA - Diensten - Onderzoek"
context["NOI2003"] = "UA - Diensten - Onderzoek"
context["CHROZ"] = "UA - Diensten - Onderzoek"
context["CAPRI"] = "UA - Diensten - Onderzoek"
context["TONYRESARCH"] = "UA - Diensten - Onderzoek"
context["METHUSALEM"] = "UA - Diensten - Onderzoek"
context["TOP20102013"] = "UA - Diensten - Onderzoek"
context["RESEARCHEVALPHYSICS"] = "UA - Diensten - Onderzoek"
context["ONDERZK2"] = "UA - Diensten - Onderzoek"

context["FUFL"] = "UA - Diensten - Personeel"
context["PERSDIENS"] = "UA - Diensten - Personeel"
context["PERSINFO"] = "UA - Diensten - Personeel"
context["PERSINFOPERSINFO"] = "UA - Diensten - Personeel"
context["PERSPORT"] = "UA - Diensten - Personeel"
context["PROCBOEK"] = "UA - Diensten - Personeel"
context["VACATURES"] = "UA - Diensten - Personeel"
context["PERSONEEL"] = "UA - Diensten - Personeel"
context["DIENSTH"] = "UA - Diensten - Personeel"
context["VABAP"] = "UA - Diensten - Personeel"
context["DEPTPERSONEEL"] = "UA - Diensten - Personeel"
context["PERSONEEL2"] = "UA - Diensten - Personeel"
context["PERSONEELSVERENIGING"] = "UA - Diensten - Personeel"

context["KOK"] = "UA - Diensten - Stafdiensten Rector"
context["brantijser"] = "UA - Diensten - Stafdiensten Rector"

context["PAVO"] = "UA - Diensten - Wmd."
context["WMDRAAD"] = "UA - Diensten - Wmd."
context["WETCOM"] = "UA - Diensten - Wmd."
context["GELIJKEKANSEN"] = "UA - Diensten - Wmd."
context["DOTONTW"] = "UA - Diensten - Wmd."
context["SGMVO"] = "UA - Diensten - Wmd."
context["DUURONT"] = "UA - Diensten - Wmd."
context["MVOND"] = "UA - Diensten - Wmd."
context["KLIMAATWEEK"] = "UA - Diensten - Wmd."


context["VAOPAVO"] = "UA - Diensten - Studentgerichte diensten"
context["ADSTUD"] = "UA - Diensten - Studentgerichte diensten"
context["DIS"] = "UA - Diensten - Studentgerichte diensten"
context["VAOPAVO"] = "UA - Diensten - Studentgerichte diensten"
context["contactpersonenslb"] = "UA - Diensten - Studentgerichte diensten"
context["STUDENTENRAAD"] = "UA - Diensten - Studentgerichte diensten"
context["EITEI"] = "UA - Diensten - Studentgerichte diensten"
context["MASTERS"] = "UA - Diensten - Studentgerichte diensten"
context["ONTHAALDAG"] = "UA - Diensten - Studentgerichte diensten"
context["SEPTEMBER"] = "UA - Diensten - Studentgerichte diensten"
context["ECV"] = "UA - Diensten - Studentgerichte diensten"
context["DSSBTRAININGEN"] = "UA - Diensten - Studentgerichte diensten"
context["NDLANTWERPEN"] = "UA - Diensten - Studentgerichte diensten"
context["CULTUURAANUA"] = "UA - Diensten - Studentgerichte diensten"
context["SOULINABOWL"] = "UA - Diensten - Studentgerichte diensten"
context["OPENLESDAGEN"] = "UA - Diensten - Studentgerichte diensten"
context["STUDIELOOPBAANBEGELEIDING"] = "UA - Diensten - Studentgerichte diensten"
context["ECEI"] = "UA - Diensten - Studentgerichte diensten"
context["LEERONSKENNEN"] = "UA - Diensten - Studentgerichte diensten"
context["STUDENTENCLUBS"] = "UA - Diensten - Studentgerichte diensten"

context["VERZEKER"] = "UA - Diensten - Verzekeringen"

context["PBW"] = "UA - Diensten - PBW"

context["IDKIJK"] = "UA - Diensten - Dep Communicatie"
context["INTRAM"] = "UA - Diensten - Dep Communicatie"
context["NEWS"] = "UA - Diensten - Dep Communicatie"
context["EREDOC"] = "UA - Diensten - Dep Communicatie"
context["HUISSTIJL"] = "UA - Diensten - Dep Communicatie"
context["EREDOC2006"] = "UA - Diensten - Dep Communicatie"
context["KINDERUNIVERSITEIT"] = "UA - Diensten - Dep Communicatie"
context["PLAATSING"] = "UA - Diensten - Dep Communicatie"
context["GVASTATS"] = "UA - Diensten - Dep Communicatie"
context["COMMUNICATIE"] = "UA - Diensten - Dep Communicatie"
context["INSCHRPERSFEEST"] = "UA - Diensten - Dep Communicatie"

context["BESTCOL"] = "UA - Diensten - Bestuurlijk"
context["COLBEHEER"] = "UA - Diensten - Bestuurlijk"
context["CVD"] = "UA - Diensten - Bestuurlijk"
context["HOGERAAD"] = "UA - Diensten - Bestuurlijk"
context["HUISHREGL"] = "UA - Diensten - Bestuurlijk"
context["ORGANOGRA"] = "UA - Diensten - Bestuurlijk"
context["REGLEM"] = "UA - Diensten - Bestuurlijk"
context["RVB"] = "UA - Diensten - Bestuurlijk"
context["VERGADER"] = "UA - Diensten - Bestuurlijk"
context["AUDIT"] = "UA - Diensten - Bestuurlijk"
context["BESTUUR"] = "UA - Diensten - Bestuurlijk"
context["COBAD"] = "UA - Diensten - Bestuurlijk"
context["INTERNBELEID"] = "UA - Diensten - Bestuurlijk"

context["PASDIENST"] = "Diensten - Levensbeschouwelijk"
context["USAB"] = "Diensten - Levensbeschouwelijk"
context["VERKENNINGSDAGEN"] = "Diensten - Levensbeschouwelijk"
context["VERKENNINGSDAGENCMI"] = "Diensten - Levensbeschouwelijk"
context["VERKENNINGSDAGENCST"] = "Diensten - Levensbeschouwelijk"
context["ZOMERSCHOOL"] = "Diensten - Levensbeschouwelijk"
context["LUSTENZONDE"] = "Diensten - Levensbeschouwelijk"
context["VRIJZINNIG"] = "Diensten - Levensbeschouwelijk"
context["OVERLIJDEN"] = "Diensten - Levensbeschouwelijk"


context["EAIE"] = "UA - Diensten - Internationaal"
context["DISTESTNL"] = "UA - Diensten - Internationaal"
context["DISTESTE"] = "UA - Diensten - Internationaal"
context["BUDDY"] = "UA - Diensten - Internationaal"
context["PARTNERINFO"] = "UA - Diensten - Internationaal"
context["EAIE08"] = "UA - Diensten - Internationaal"
context["ECTS"] = "UA - Diensten - Internationaal"
context["ASU"] = "UA - Diensten - Internationaal"
context["MIJNVERHAAL"] = "UA - Diensten - Internationaal"
context["PRACTICALGUIDE"] = "UA - Diensten - Internationaal"
context["PROMOB"] = "UA - Diensten - Internationaal"
context["EMCHINA"] = "UA - Diensten - Internationaal"
context["EADIC"] = "UA - Diensten - Internationaal"
context["EMUA"] = "UA - Diensten - Internationaal"
context["EMUNDUS20"] = "UA - Diensten - Internationaal"


context["CBO"] = "UA - Centra en instituten"
context["CENINS"] = "UA - Centra en instituten"
context["CIMDA"] = "UA - Centra en instituten"
context["CMS"] = "UA - Centra en instituten"
context["CMSENG"] = "UA - Centra en instituten"
context["CMSESP"] = "UA - Centra en instituten"
context["CVA"] = "UA - Centra en instituten"
context["CVBB"] = "UA - Centra en instituten"
context["IJS"] = "UA - Centra en instituten"
context["ISLN"] = "UA - Centra en instituten"
context["MILKND"] = "UA - Centra en instituten"
context["PIETERGIL"] = "UA - Centra en instituten"
context["TESTCENTR"] = "UA - Centra en instituten"
context["UATALIN"] = "UA - Centra en instituten"
context["ICTLENG"] = "UA - Centra en instituten"
context["ICTLFR"] = "UA - Centra en instituten"
context["ICTLNL"] = "UA - Centra en instituten"
context["STATUA"] = "UA - Centra en instituten"
context["IJSENG"] = "UA - Centra en instituten"
context["ISUA"] = "UA - Centra en instituten"
context["INDIASC"] = "UA - Centra en instituten"
context["MOBILITY"] = "UA - Centra en instituten"
context["STEM"] = "UA - Centra en instituten"
context["SPIRE"] = "UA - Centra en instituten"
context["EIMTL"] = "UA - Centra en instituten"
context["CEMIS"] = "UA - Centra en instituten"
context["LINGUAPOLISFR"] = "UA - Centra en instituten"
context["LINGUAPOLISEN"] = "UA - Centra en instituten"
context["TOGA"] = "UA - Centra en instituten"
context["ICOR"] = "UA - Centra en instituten"
context["ELA"] = "UA - Centra en instituten"
context["TAALLEERDER"] = "UA - Centra en instituten"
context["MIDP"] = "UA - Centra en instituten"
context["LCV"] = "UA - Centra en instituten"
context["VAXINFECTIO"] = "UA - Centra en instituten"
context["CALL2008"] = "UA - Centra en instituten"
context["CAS"] = "UA - Centra en instituten"
context["MONITORAAT"] = "UA - Centra en instituten"
context["LINGUAPOLIS_OPENDEUR"] = "UA - Centra en instituten"
context["ISC"] = "UA - Centra en instituten"
context["SEPIA"] = "UA - Centra en instituten"
context["LINGUANLPART"] = "UA - Centra en instituten"
context["LINGUANLBEDR"] = "UA - Centra en instituten"
context["LINGUANLOO"] = "UA - Centra en instituten"
context["LINGUANLAC"] = "UA - Centra en instituten"
context["LINGUANLANDERE"] = "UA - Centra en instituten"
context["LINGUANL"] = "UA - Centra en instituten"
context["CALL2010"] = "UA - Centra en instituten"
context["LINGUANLEXTRA"] = "UA - Centra en instituten"
context["ESM"] = "UA - Centra en instituten"
context["SBO"] = "UA - Centra en instituten"
context["LINGUASUMMERSCHOOL"] = "UA - Centra en instituten"
context["SHAREPROJECT"] = "UA - Centra en instituten"
context["MIGRATIEHERINNEREN"] = "UA - Centra en instituten"
context["LINGUAFR"] = "UA - Centra en instituten"
context["LINGUAEN"] = "UA - Centra en instituten"
context["LINGUAFREXTRA"] = "UA - Centra en instituten"
context["LINGUAENEXTRA"] = "UA - Centra en instituten"
context["LINGUAFRANDERE"] = "UA - Centra en instituten"
context["LINGUAENANDERE"] = "UA - Centra en instituten"
context["LINGUAFRAC"] = "UA - Centra en instituten"
context["LINGUAENAC"] = "UA - Centra en instituten"
context["LINGUAFROO"] = "UA - Centra en instituten"
context["LINGUAENOO"] = "UA - Centra en instituten"
context["LINGUAFRBEDR"] = "UA - Centra en instituten"
context["LINGUAENBEDR"] = "UA - Centra en instituten"
context["LINGUAFRPART"] = "UA - Centra en instituten"
context["LINGUAENPART"] = "UA - Centra en instituten"
context["ENQUETEOCMW"] = "UA - Centra en instituten"
context["WATERTECHNOLOGY"] = "UA - Centra en instituten"
context["IMAMS"] = "UA - Centra en instituten"
context["DEUTSCHCAFE"] = "UA - Centra en instituten"
context["VADEMECUM"] = "UA - Centra en instituten"
context["CZT"] = "UA - Centra en instituten"
context["ORGSYNTH"] = "UA - Centra en instituten"
context["CEMISNL"] = "UA - Centra en instituten"
context["GRUNDTVIG"] = "UA - Centra en instituten"
context["IMAMSE"] = "UA - Centra en instituten"
context["IMAMSF"] = "UA - Centra en instituten"
context["IMAMSA"] = "UA - Centra en instituten"
context["CEMISUK"] = "UA - Centra en instituten"
context["OPRIT14"] = "UA - Centra en instituten"
context["ELSIN"] = "UA - Centra en instituten"

context["ACM"] = "UA - Faculteiten - Rechten"
context["FACREC"] = "UA - Faculteiten - Rechten"
context["ICW"] = "UA - Faculteiten - Rechten"
context["IELSP"] = "UA - Faculteiten - Rechten"
context["STUDSEMSR"] = "UA - Faculteiten - Rechten"
context["CIKORECHTEN"] = "UA - Faculteiten - Rechten"
context["ILAG2005"] = "UA - Faculteiten - Rechten"
context["ILAG2007"] = "UA - Faculteiten - Rechten"
context["ogr"] = "UA - Faculteiten - Rechten"
context["FISCRECHT"] = "UA - Faculteiten - Rechten"
context["STRAFRECHT"] = "UA - Faculteiten - Rechten"
context["BURGRECHT"] = "UA - Faculteiten - Rechten"
context["ECOVEN"] = "UA - Faculteiten - Rechten"
context["GESCHILOPL"] = "UA - Faculteiten - Rechten"
context["EUROPEESRECHT"] = "UA - Faculteiten - Rechten"
context["STAATSBESTUURSRECHT"] = "UA - Faculteiten - Rechten"
context["SOCIAALRECHT"] = "UA - Faculteiten - Rechten"
context["SOCIALLAW"] = "UA - Faculteiten - Rechten"
context["ORA"] = "UA - Faculteiten - Rechten"
context["UALS"] = "UA - Faculteiten - Rechten"
context["EMR"] = "UA - Faculteiten - Rechten"
context["KUNSTENRECHT"] = "UA - Faculteiten - Rechten"
context["FAMILIERECHT"] = "UA - Faculteiten - Rechten"
context["CHILDRENSRIGHTS"] = "UA - Faculteiten - Rechten"
context["KINDERRECHTEN"] = "UA - Faculteiten - Rechten"
context["ZEERECHT"] = "UA - Faculteiten - Rechten"
context["PARA"] = "UA - Faculteiten - Rechten"
context["WEST"] = "UA - Faculteiten - Rechten"
context["ISE"] = "UA - Faculteiten - Rechten"
context["SOCIALECONOMY"] = "UA - Faculteiten - Rechten"
context["CDR"] = "UA - Faculteiten - Rechten"
context["ICCR"] = "UA - Faculteiten - Rechten"
context["60JAARUVRM"] = "UA - Faculteiten - Rechten"
context["RRWAC"] = "UA - Faculteiten - Rechten"
context["RECHTENONDERWIJS"] = "UA - Faculteiten - Rechten"
context["ONDERZOEKSTRAFTOEMETING"] = "UA - Faculteiten - Rechten"


context["TEWENG"] = "UA - Faculteiten - Tew"
context["TEWHI"] = "UA - Faculteiten - Tew"
context["TEWDUITS"] = "UA - Faculteiten - Tew"
context["TEWSPAANS"] = "UA - Faculteiten - Tew"
context["TEWENGL"] = "UA - Faculteiten - Tew"
context["CYCLES"] = "UA - Faculteiten - Tew"
context["HSWENNEN"] = "UA - Faculteiten - Tew"
context["TEWFRANS"] = "UA - Faculteiten - Tew"
context["KWARTAALTIJDSCHRIFT"] = "UA - Faculteiten - Tew"
context["ONDERNEMERSCHAP"] = "UA - Faculteiten - Tew"
context["jfornero"] = "UA - Faculteiten - Tew"
context["TEWINTERCBC"] = "UA - Faculteiten - Tew"
context["gedragsexperiment"] = "UA - Faculteiten - Tew"
context["PREEMERITAATBRAECKE"] = "UA - Faculteiten - Tew"
context["studiewijzer"] = "UA - Faculteiten - Tew"
context["KWALITEITSZORGTEW"] = "UA - Faculteiten - Tew"
context["MBA"] = "UA - Faculteiten - Tew"
context["RECS"] = "UA - Faculteiten - Tew"
context["studiewijzer2"] = "UA - Faculteiten - Tew"
context["OOPGENERIEK"] = "UA - Faculteiten - Tew"
context["OOPGENERIEKD"] = "UA - Faculteiten - Tew"
context["MEP"] = "UA - Faculteiten - Tew"
context["OOPTEW"] = "UA - Faculteiten - Tew"
context["OOPTEWBK"] = "UA - Faculteiten - Tew"
context["OOPTEWEB"] = "UA - Faculteiten - Tew"
context["OOPHI"] = "UA - Faculteiten - Tew"
context["OOPHIBI"] = "UA - Faculteiten - Tew"
context["OOPSEW"] = "UA - Faculteiten - Tew"


context["IBC"] = "UA - Faculteiten - Tew - Int. Bedrijfscommunicatie"
context["IBCDIO"] = "UA - Faculteiten - Tew - Int. Bedrijfscommunicatie"
context["GABC"] = "UA - Faculteiten - Tew - Int. Bedrijfscommunicatie"


context["ACF"] = "UA - Faculteiten - Tew - Accounting en finan."
context["CORPORATEFINANCEDAY2009"] = "UA - Faculteiten - Tew - Accounting en finan."
context["ENTREPRENEURSHIPDAY2010"] = "UA - Faculteiten - Tew - Accounting en finan."

context["AEC"] = "UA - Faculteiten - Tew - Algemene economie"
context["GD10826"] = "UA - Faculteiten - Tew - Algemene economie"

context["MIS"] = "UA - Faculteiten - Tew - Beleidsinformatica"
context["OSS2010DC"] = "UA - Faculteiten - Tew - Beleidsinformatica"

context["IMD"] = "UA - Faculteiten - Tew - Int. econ. int. man."
context["IBD"] = "UA - Faculteiten - Tew - Int. econ. int. man."
context["CAMPREC"] = "UA - Faculteiten - Tew - Int. econ. int. man."


context["MNG"] = "UA - Faculteiten - Tew - Management"
context["QUADEM"] = "UA - Faculteiten - Tew - Management"
context["DJSANDPRODUCERS"] = "UA - Faculteiten - Tew - Management"
context["MVO"] = "UA - Faculteiten - Tew - Management"
context["ODYSSEUS"] = "UA - Faculteiten - Tew - Management"
context["FVC"] = "UA - Faculteiten - Tew - Management"
context["ACEDNEW"] = "UA - Faculteiten - Tew - Management"
context["DIGITALECOMMUNICATIE1"] = "UA - Faculteiten - Tew - Management"
context["DIGITALECOMMUNICATIE2"] = "UA - Faculteiten - Tew - Management"
context["DIGITALECOMMUNICATIE3"] = "UA - Faculteiten - Tew - Management"
context["MNG2"] = "UA - Faculteiten - Tew - Management"


context["MKT"] = "UA - Faculteiten - Tew - Marketing"

context["MTT"] = "UA - Faculteiten - Tew - Milieu en technologieman."
context["STEM"] = "UA - Faculteiten - Tew - Milieu en technologieman."
context["PEPAM"] = "UA - Faculteiten - Tew - Milieu en technologieman."
context["APL"] = "UA - Faculteiten - Tew - Milieu en technologieman."
context["ARGOSS"] = "UA - Faculteiten - Tew - Milieu en technologieman."
context["METEN"] = "UA - Faculteiten - Tew - Milieu en technologieman."
context["BELSPO-FORUM"] = "UA - Faculteiten - Tew - Milieu en technologieman."


context["TPR"] = "UA - Faculteiten - Tew - Transp. en ruimt. econ."
context["TPM"] = "UA - Faculteiten - Tew - Transp. en ruimt. econ."
context["GOEDERENSTROMEN"] = "UA - Faculteiten - Tew - Transp. en ruimt. econ."
context["WATER"] = "UA - Faculteiten - Tew - Transp. en ruimt. econ."
context["WEGCAPACITEIT"] = "UA - Faculteiten - Tew - Transp. en ruimt. econ."
context["WEGOTM"] = "UA - Faculteiten - Tew - Transp. en ruimt. econ."
context["MKBA"] = "UA - Faculteiten - Tew - Transp. en ruimt. econ."
context["HINTERLAND"] = "UA - Faculteiten - Tew - Transp. en ruimt. econ."
context["WEGVOKA"] = "UA - Faculteiten - Tew - Transp. en ruimt. econ."
context["ENQUETEFEDIS"] = "UA - Faculteiten - Tew - Transp. en ruimt. econ."
context["ENQUETEVVSG"] = "UA - Faculteiten - Tew - Transp. en ruimt. econ."
context["PIEKCOLRUYT"] = "UA - Faculteiten - Tew - Transp. en ruimt. econ."


context["WIS"] = "UA - Faculteiten - Tew - Wisk. statistiek en actua"
context["MASSEMINARIE2007"] = "UA - Faculteiten - Tew - Wisk. statistiek en actua"
context["DOE"] = "UA - Faculteiten - Tew - Wisk. statistiek en actua"
context["BENBIS"] = "UA - Faculteiten - Tew - Wisk. statistiek en actua"

context["RISKMAN"] = "UA - Faculteiten - Tew - Conference"
context["TEWNAMES"] = "UA - Faculteiten - Tew - Conference"
context["STEDENBELEID"] = "UA - Faculteiten - Tew - Conference"


context["CIKOWET"] = "UA - Faculteiten - Wetenschappen"
context["DEPBIO"] = "UA - Faculteiten - Wetenschappen"
context["FACWET"] = "UA - Faculteiten - Wetenschappen"
context["SCHOOLBEZ"] = "UA - Faculteiten - Wetenschappen"
context["CURRMK"] = "UA - Faculteiten - Wetenschappen"
context["BIOINF"] = "UA - Faculteiten - Wetenschappen"
context["MICROTOMO"] = "UA - Faculteiten - Wetenschappen"
context["BIOTUIN"] = "UA - Faculteiten - Wetenschappen"
context["TREFDAG"] = "UA - Faculteiten - Wetenschappen"
context["WETTEST"] = "UA - Faculteiten - Wetenschappen"
context["EXPWETNED"] = "UA - Faculteiten - Wetenschappen"
context["ECORISE"] = "UA - Faculteiten - Wetenschappen"


context["DEPBIO"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["ECOBE"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["EVOBIO"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["ISTA"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["NANOBIOLOGY"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["WATERSYS"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["SQA6"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["CEPRO"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["BIFY"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["SPITSBERGEN"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["BIORUIMTE"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["ECO"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["DECO"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["PLECO"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["LUSI"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["BENEFIETCONCERT"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["BIODIVERSITEIT"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["EVECO"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["IWRM"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["ALIENIMPACT"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["FUNMORPH"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["ETHOLOGIE"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["ETHOLOGY"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["MPBNL"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["ECOBENEW"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["MANUDYN"] = "UA - Faculteiten - Wetenschappen - Biologie"
context["IBIS_ANTWERP2011"] = "UA - Faculteiten - Wetenschappen - Biologie"

context["SCHEIKUN"] = "UA - Faculteiten - Wetenschappen - Chemie"
context["STRUCCHEM"] = "UA - Faculteiten - Wetenschappen - Chemie"
context["ADSKAT"] = "UA - Faculteiten - Wetenschappen - Chemie"
context["EUROANALYSOSXIV"] = "UA - Faculteiten - Wetenschappen - Chemie"
context["INSIDEPOREYR"] = "UA - Faculteiten - Wetenschappen - Chemie"
context["MONITORAATCHEMIE"] = "UA - Faculteiten - Wetenschappen - Chemie"
context["RESEARCHEVALUATIONCHEMISTRY"] = "UA - Faculteiten - Wetenschappen - Chemie"
context["CAC2010"] = "UA - Faculteiten - Wetenschappen - Chemie"
context["ENMIX"] = "UA - Faculteiten - Wetenschappen - Chemie"


context["NATUURKUNDE"] = "UA - Faculteiten - Wetenschappen - Fysica"
context["WETNAT01"] = "UA - Faculteiten - Wetenschappen - Fysica"
context["MASSSPEC"] = "UA - Faculteiten - Wetenschappen - Fysica"
context["NANO"] = "UA - Faculteiten - Wetenschappen - Fysica"
context["MEDELEC"] = "UA - Faculteiten - Wetenschappen - Fysica"
context["TFVS"] = "UA - Faculteiten - Wetenschappen - Fysica"
context["TFVSE"] = "UA - Faculteiten - Wetenschappen - Fysica"
context["QUANTIVIAM"] = "UA - Faculteiten - Wetenschappen - Fysica"
context["BIMEF"] = "UA - Faculteiten - Wetenschappen - Fysica"
context["TQC"] = "UA - Faculteiten - Wetenschappen - Fysica"
context["AUREA"] = "UA - Faculteiten - Wetenschappen - Fysica"
context["EDF"] = "UA - Faculteiten - Wetenschappen - Fysica"
context["AUREANL"] = "UA - Faculteiten - Wetenschappen - Fysica"

context["TBW"] = "UA - Faculteiten - Wetenschappen - Toeg. biologische wet."
context["AUC"] = "UA - Faculteiten - Wetenschappen - Toeg. biologische wet."
context["BOOMONDERZOEK"] = "UA - Faculteiten - Wetenschappen - Toeg. biologische wet."
context["BIOHYPE"] = "UA - Faculteiten - Wetenschappen - Toeg. biologische wet."
context["ALABO"] = "UA - Faculteiten - Wetenschappen - Toeg. biologische wet."

context["DIGULL"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["FACLW"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["GESCH"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["IOIW"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["MEMORIA"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["OGF"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["POSTCOL"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["RUUSBROEC"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["TAALLETTE"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["ILE"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["MASAMSTU"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["LANGSTUDIES"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["GJS"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["MPC"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["CCICLA"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["LWTEST"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["TESTMPC"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["MPS"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["OPENLESTLET"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["OPENLESGESCH"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["OPENLESWIJSB"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["FACARTS"] = "UA - Faculteiten - Letteren en Wijsbeg."
context["MPC2"] = "UA - Faculteiten - Letteren en Wijsbeg."

context["GESCH"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["FOTODB"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis" 
context["ORTELIUS"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["CULTGESCH"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["KLANKSTAD"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["POLGESCH"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis" 
context["LOCALMEMORIES"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["CIVILSOCIETY"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["SEXUALMODERNITY"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["STADSKLANKEN18"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["SOUNDSOFTHECITY18"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["ANTWERPRENAISS"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["PAPERS-HTCS"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["GARRIOCH"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["REDACTIE_STADSGESCHIEDENIS"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["BIOGRAFIEVANEENSTAD"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"
context["BOOKCIVILSOCIETY"] = "UA - Faculteiten - Letteren en Wijsbeg. - Geschiedenis"

context["TESTTHOMAS"] = "UA - Faculteiten - Letteren en Wijsbeg. - Letterkunde"
context["THEATERWET"] = "UA - Faculteiten - Letteren en Wijsbeg. - Letterkunde"
context["LOCUSOFTRAGEDY"] = "UA - Faculteiten - Letteren en Wijsbeg. - Letterkunde"
context["KUNSTFALEN"] = "UA - Faculteiten - Letteren en Wijsbeg. - Letterkunde"
context["THEATER2"] = "UA - Faculteiten - Letteren en Wijsbeg. - Letterkunde"
context["WOORDENBEELD"] = "UA - Faculteiten - Letteren en Wijsbeg. - Letterkunde"
context["CHILDLIT"] = "UA - Faculteiten - Letteren en Wijsbeg. - Letterkunde"
context["GEGENDENSTRICH"] = "UA - Faculteiten - Letteren en Wijsbeg. - Letterkunde"


context["DEPTAALK"] = "UA - Faculteiten - Letteren en Wijsbeg. - Taalkunde"
context["CHRONOS7FR"] = "UA - Faculteiten - Letteren en Wijsbeg. - Taalkunde"
context["EDINBURGHIPA"] = "UA - Faculteiten - Letteren en Wijsbeg. - Taalkunde"
context["CHRONOS7"] = "UA - Faculteiten - Letteren en Wijsbeg. - Taalkunde"
context["MOYEN"] = "UA - Faculteiten - Letteren en Wijsbeg. - Taalkunde"
context["ACWRITING"] = "UA - Faculteiten - Letteren en Wijsbeg. - Taalkunde"
context["ACWRFB"] = "UA - Faculteiten - Letteren en Wijsbeg. - Taalkunde"
context["VWM"] = "UA - Faculteiten - Letteren en Wijsbeg. - Taalkunde"
context["EMERITAATFRANSDAEMS"] = "UA - Faculteiten - Letteren en Wijsbeg. - Taalkunde"
context["ABLA2009"] = "UA - Faculteiten - Letteren en Wijsbeg. - Taalkunde"


context["RELEMO"] = "UA - Faculteiten - Letteren en Wijsbeg. - Wijsbegeerte"
context["WIJSBEG"] = "UA - Faculteiten - Letteren en Wijsbeg. - Wijsbegeerte"
context["philosophyofmind"] = "UA - Faculteiten - Letteren en Wijsbeg. - Wijsbegeerte"
context["WBTERROR"] = "UA - Faculteiten - Letteren en Wijsbeg. - Wijsbegeerte"
context["VAF"] = "UA - Faculteiten - Letteren en Wijsbeg. - Wijsbegeerte"
context["CONS"] = "UA - Faculteiten - Letteren en Wijsbeg. - Wijsbegeerte"
context["HUMECONFERENCE"] = "UA - Faculteiten - Letteren en Wijsbeg. - Wijsbegeerte"
context["Wijsbegeerte"] = "UA - Faculteiten - Letteren en Wijsbeg. - Wijsbegeerte"
context["PRSL2009"] = "UA - Faculteiten - Letteren en Wijsbeg. - Wijsbegeerte"
context["LEERSTOELCIVISMUNDI"] = "UA - Faculteiten - Letteren en Wijsbeg. - Wijsbegeerte"
context["METAPHORSPHILOSOPHY"] = "UA - Faculteiten - Letteren en Wijsbeg. - Wijsbegeerte"


context["MASOC"] = "UA - Faculteiten - Pol. en Soc. Wet."
context["PSW"] = "UA - Faculteiten - Pol. en Soc. Wet."
context["m2p"] = "UA - Faculteiten - Pol. en Soc. Wet."
context["LTIS"] = "UA - Faculteiten - Pol. en Soc. Wet."
context["UAMB"] = "UA - Faculteiten - Pol. en Soc. Wet."
context["MTSO"] = "UA - Faculteiten - Pol. en Soc. Wet."
context["SOCRATES2007"] = "UA - Faculteiten - Pol. en Soc. Wet."
context["DIPLOGEO"] = "UA - Faculteiten - Pol. en Soc. Wet."
context["PSWSTAGE"] = "UA - Faculteiten - Pol. en Soc. Wet."
context["RESEARCHEVALUATIONPSS"] = "UA - Faculteiten - Pol. en Soc. Wet."

context["CWEDU"] = "UA - Faculteiten - Pol. en Soc. Wet. - Communicatiewetensch."
context["CWONW"] = "UA - Faculteiten - Pol. en Soc. Wet. - Communicatiewetensch."
context["CWONZ"] = "UA - Faculteiten - Pol. en Soc. Wet. - Communicatiewetensch."
context["CWRES"] = "UA - Faculteiten - Pol. en Soc. Wet. - Communicatiewetensch."
context["MASFIL"] = "UA - Faculteiten - Pol. en Soc. Wet. - Communicatiewetensch."
context["CYBERPESTEN"] = "UA - Faculteiten - Pol. en Soc. Wet. - Communicatiewetensch."
context["TIRO"] = "UA - Faculteiten - Pol. en Soc. Wet. - Communicatiewetensch."
context["VISUALCULTURE"] = "UA - Faculteiten - Pol. en Soc. Wet. - Communicatiewetensch."
context["PSWSTAGES"] = "UA - Faculteiten - Pol. en Soc. Wet. - Communicatiewetensch."

context["SWW"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["OWV"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["UGIS"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["OCW"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["OASES"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["OASESE"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["OCMWENQUETE"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["INTEGRATIEKAART"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["OASESTEST"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["OASESETEST"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["FACIT"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["CONVENANTEN"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["FACIT2"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["RSWUA"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["ENQUETEDAKENTHUISLOOSHEID"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"
context["QUESTIONNAIRESANSABRISME"] = "UA - Faculteiten - Pol. en Soc. Wet. - Sociologie"

context["FBD"] = "UA - Faculteiten - Fbd"
context["FBDTEST"] = "UA - Faculteiten - Fbd"
context["IPVLS"] = "UA - Faculteiten - Fbd"
context["PAVODAP"] = "UA - Faculteiten - Fbd"
context["PAVOMM"] = "UA - Faculteiten - Fbd"
context["PAVOKWO"] = "UA - Faculteiten - Fbd"
context["PAVOOND"] = "UA - Faculteiten - Fbd"
context["ECD"] = "UA - Faculteiten - Fbd"
context["INFODAGFBD"] = "UA - Faculteiten - Fbd"
context["FBDE"] = "UA - Faculteiten - Fbd"
context["ONDERZOEKSDAGFBD"] = "UA - Faculteiten - Fbd"


context["BMW"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["BMW1"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["CWL"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["FRONTIER"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["MABIOBE"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["MABMW"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["BMWALL"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["BMWDR"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["IAPP631"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["BIOMEDISCHE"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["BIOCHEMIE"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["MHLAB"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["O2BIP2010"] = "UA - Faculteiten - Fbd - Biomedische Wet."
context["PPS"] = "UA - Faculteiten - Fbd - Biomedische Wet."

context["DGK"] = "UA - Faculteiten - Fbd - Diergeneeskundige Wet."
context["PAVOPDK"] = "UA - Faculteiten - Fbd - Diergeneeskundige Wet."
context["AARG"] = "UA - Faculteiten - Fbd - Diergeneeskundige Wet."
context["DPL"] = "UA - Faculteiten - Fbd - Diergeneeskundige Wet."
context["AEHD"] = "UA - Faculteiten - Fbd - Diergeneeskundige Wet."
context["JOINTMEETINGAGNAV"] = "UA - Faculteiten - Fbd - Diergeneeskundige Wet."

context["GENHOME"] = "UA - Faculteiten - Geneeskunde"
context["GENKLIN"] = "UA - Faculteiten - Geneeskunde"
context["GENONZ"] = "UA - Faculteiten - Geneeskunde"
context["GENORG"] = "UA - Faculteiten - Geneeskunde"
context["EWGCCE"] = "UA - Faculteiten - Geneeskunde"
context["HPVINFO"] = "UA - Faculteiten - Geneeskunde"
context["IMMUNOLOGY"] = "UA - Faculteiten - Geneeskunde"
context["PNEUMO"] = "UA - Faculteiten - Geneeskunde"
context["ESOC"] = "UA - Faculteiten - Geneeskunde"
context["FGENVAD"] = "UA - Faculteiten - Geneeskunde"
context["FGENOND"] = "UA - Faculteiten - Geneeskunde"
context["ONCOLOGIE"] = "UA - Faculteiten - Geneeskunde"
context["MVVSYMPOSIUM"] = "UA - Faculteiten - Geneeskunde"
context["WARMONTH"] = "UA - Faculteiten - Geneeskunde"
context["CHAENGLISH"] = "UA - Faculteiten - Geneeskunde"
context["ENOHE2007"] = "UA - Faculteiten - Geneeskunde"
context["AMRU"] = "UA - Faculteiten - Geneeskunde"
context["KWALITEITSZORG"] = "UA - Faculteiten - Geneeskunde"
context["CHAUNITHA"] = "UA - Faculteiten - Geneeskunde"
context["GRATISTESTS"] = "UA - Faculteiten - Geneeskunde"
context["VAARDIGHEDENCONGRES"] = "UA - Faculteiten - Geneeskunde"
context["VOVENQUETE"] = "UA - Faculteiten - Geneeskunde"
context["geneeskundetest"] = "UA - Faculteiten - Geneeskunde"
context["GRATISFILM"] = "UA - Faculteiten - Geneeskunde"
context["HIVCONTROL"] = "UA - Faculteiten - Geneeskunde"
context["SLEEP"] = "UA - Faculteiten - Geneeskunde"
context["HANDICAP"] = "UA - Faculteiten - Geneeskunde"
context["HPVVRAGENLIJST"] = "UA - Faculteiten - Geneeskunde"
context["KINDERPNEUMO"] = "UA - Faculteiten - Geneeskunde"
context["CEVSUMMERSCHOOL"] = "UA - Faculteiten - Geneeskunde"
context["ONCOLOGY"] = "UA - Faculteiten - Geneeskunde"
context["CHERMID"] = "UA - Faculteiten - Geneeskunde"
context["SIMID"] = "UA - Faculteiten - Geneeskunde"
context["PATHOPHYSIOLOGY"] = "UA - Faculteiten - Geneeskunde"
context["GENEESKUNDENEW"] = "UA - Faculteiten - Geneeskunde"
context["DAFFODIL"] = "UA - Faculteiten - Geneeskunde"
context["CEVVACCINOLOGYTRAINING"] = "UA - Faculteiten - Geneeskunde"
context["PRENATALEDIAGNOSTIEK"] = "UA - Faculteiten - Geneeskunde"
context["EADSM"] = "UA - Faculteiten - Geneeskunde"
context["IUC_UL"] = "UA - Faculteiten - Geneeskunde"


context["FARMACIE"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["FARMANT"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["MEDSCH"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["COGNOSIE"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["BROMATO"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["MICROBIO"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["MEDBIO"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["GALENICA"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["TOXICO"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["FYSIOFARM"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["MASSS"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["IGMP"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["PHYSIOLO"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["ADDN"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["RESEARCHEVALUATIONPHARMACY"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["UCAG2"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."
context["MEDGEN"] = "UA - Faculteiten - Fbd - Farmaceutische Wetensch."

context["IBW"] = "UA - Instituut Onderw. en inf.wet"
context["IOIW"] = "UA - Instituut Onderw. en inf.wet"
context["EDUBRON"] = "UA - Instituut Onderw. en inf.wet"
context["DIDANED"] = "UA - Instituut Onderw. en inf.wet"
context["VFO2006"] = "UA - Instituut Onderw. en inf.wet"
context["LERARENOPL"] = "UA - Instituut Onderw. en inf.wet"
context["ASSESSMENT"] = "UA - Instituut Onderw. en inf.wet"
context["IBWNEW"] = "UA - Instituut Onderw. en inf.wet"
context["IBWNEWENG"] = "UA - Instituut Onderw. en inf.wet"
context["ENIRDELM2009"] = "UA - Instituut Onderw. en inf.wet"
context["REPRO"] = "UA - Instituut Onderw. en inf.wet"

context["DOCOP"] = "UA - Interfacultaire eenheden"
context["OVERBRUG"] = "UA - Interfacultaire eenheden"
context["DOCOP2"] = "UA - Interfacultaire eenheden"

context["GRALAC"] = "UA - IOB"
context["IOB"] = "UA - IOB"
context["IGLOP"] = "UA - IOB"
context["EULALIA"] = "UA - IOB"

context["WETWIN"] = "UA - Wetenschapswinkel"
context[""] = "UA - Wetenschapswinkel"

context["ALUMNI"] = "UA - Alumni"

context["LEZING"] = "UA - In de kijker"
context["FOTOVERSLAG"] = "UA - In de kijker"

context["PASFORANT"] = "UA - English"
context["ENGLISH"] = "UA - English"

context["STUDUA"] = "UA - Toekomstig student"
context["WERKSTUD"] = "UA - Toekomstig student"
context["STUDKIEZ"] = "UA - Toekomstig student"
context["WELKOMSTUDENT"] = "UA - Toekomstig student"
context["AZSTUDENT"] = "UA - Toekomstig student"

context["BESTCOL"] = "UA - Bestuursorganen"
context["COLBEHEER"] = "UA - Bestuursorganen"
context["VERKIEZINGEN"] = "UA - Bestuursorganen"

context["INTRAM"] = "UA - Intramail"

context["ARHI"] = "UA - Congressen"
context["ARHI2007"] = "UA - Congressen"
context["BUSCOM"] = "UA - Congressen"
context["STUGEN"] = "UA - Congressen"
context["ESFWORKSHOP"] = "UA - Congressen"
context["JOYCEBECKETT"] = "UA - Congressen"
context["NNV2006"] = "UA - Congressen"
context["NNVLANDPRACT"] = "UA - Congressen"
context["NNVPRACT2006"] = "UA - Congressen"
context["MCAENROAC"] = "UA - Congressen"
context["EAN2004"] = "UA - Congressen"
context["ICED"] = "UA - Congressen"
context["COMMITMENT"] = "UA - Congressen"
context["MARKTECOKUNST"] = "UA - Congressen"
context["BSS2007"] = "UA - Congressen"
context["EAUCLIMAT"] = "UA - Congressen"
context["KLIMAATWATER"] = "UA - Congressen"
context["WATERCLIMATE"] = "UA - Congressen"
context["KEKULE"] = "UA - Congressen"
context["STADSINNOVATIE"] = "UA - Congressen"


context["COURTSTUD"] = "UA - Andere"
context["PALLIA"] = "UA - Andere"
context["DUITABE"] = "UA - Andere"
context["BROMVLIEG"] = "UA - Andere"
context["TOULOUSE"] = "UA - Andere"
context["TROIKA"] = "UA - Andere"
context["FORUMLAWPHIL"] = "UA - Andere"
context["FILIPCOENEN"] = "UA - Andere"
context["WILDCARDTANZANIA"] = "UA - Andere"
context["CAREERSURVEY"] = "UA - Andere"
context["DAWKINS"] = "UA - Andere"
context["MEXICAANSEGRIEP"] = "UA - Andere"

context["OPL0602"] = "UA - Opleiding"
context["OPL0902"] = "UA - Opleiding"
context["OPL1302"] = "UA - Opleiding"
context["OPL1502"] = "UA - Opleiding"
context["OPL1602"] = "UA - Opleiding"
context["OPLKOTWEB"] = "UA - Opleiding"
context["OPLPLANTIJN"] = "UA - Opleiding"
context["OPLCDE"] = "UA - Opleiding"
context["OPLCDE1702"] = "UA - Opleiding"
context["OPLCST0203"] = "UA - Opleiding"
context["OPLCST0303"] = "UA - Opleiding"
context["OPL2MAART"] = "UA - Opleiding"
context["OPL9MAART"] = "UA - Opleiding"
context["OPL4MAART"] = "UA - Opleiding"
context["OPL11MAART"] = "UA - Opleiding"

context["ENROLL"] = "Virtuele Campus - Homepage"
context["VC"] = "Virtuele Campus - Homepage"
context["VC2"] = "Virtuele Campus - Homepage"

context["FORUM"] = "Virtuele Campus - Kruimelpad"
context["OVERVC"] = "Virtuele Campus - Kruimelpad"
context["STUDTIP"] = "Virtuele Campus - Kruimelpad"
context["STUDVOOR"] = "Virtuele Campus - Kruimelpad"
context["OVERVC2"] = "Virtuele Campus - Kruimelpad"
context["STUDTIP2"] = "Virtuele Campus - Kruimelpad"

context["COMWET"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["GESCH"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["HANING"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["HIBI"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["POLWET"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["RECHT"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["SOCIOL"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["COMWET2"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["POLWET2"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["GESCH2"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["HANING2"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["HIBI2"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["RECHT2"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["SOCIOL2"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["SEW2"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["TNL2"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["TEWBEDR2"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["TEWECBE2"] = "Virtuele Campus - Humane en Economische Wetenschappen"
context["WIJS2"] = "Virtuele Campus - Humane en Economische Wetenschappen"

context["CHEMIE"] = "Virtuele Campus - Exacte en medische wetenschappen"
context["BIOCHEM2"] = "Virtuele Campus - Exacte en medische wetenschappen"
context["BIOLOG2"] = "Virtuele Campus - Exacte en medische wetenschappen"
context["BIOWET2"] = "Virtuele Campus - Exacte en medische wetenschappen"
context["CHEMIE2"] = "Virtuele Campus - Exacte en medische wetenschappen"
context["DIERGEN2"] = "Virtuele Campus - Exacte en medische wetenschappen"
context["FARWET2"] = "Virtuele Campus - Exacte en medische wetenschappen"
context["FYSICA2"] = "Virtuele Campus - Exacte en medische wetenschappen"
context["GENEES2"] = "Virtuele Campus - Exacte en medische wetenschappen"
context["INFORM2"] = "Virtuele Campus - Exacte en medische wetenschappen"
context["TBW2"] = "Virtuele Campus - Exacte en medische wetenschappen"
context["WIS2"] = "Virtuele Campus - Exacte en medische wetenschappen"

context["CHAT"] = "Virtuele Campus - HelpSites"
context["FLIP"] = "Virtuele Campus - HelpSites"
context["virond"] = "Virtuele Campus - HelpSites"
context["VIRONDENG"] = "Virtuele Campus - HelpSites"

context["OPENING"] = "TestContexts"
context["TEST"] = "TestContexts"
context["STYLETEST"] = "TestContexts"
context["TESTJE"] = "TestContexts"
context["TESTWETWIN"] = "TestContexts"
context["TSTKAL"] = "TestContexts"
context["moetweg"] = "TestContexts"
context["testR"] = "TestContexts"
context["TESTSTIJN"] = "TestContexts"
context["TESTTHOMAS"] = "TestContexts"
context["TESTL"] = "TestContexts"
context["ICED"] = "TestContexts"
context["TESTCINDY"] = "TestContexts"
context["HPNEW"] = "TestContexts"
context["HPNEW1"] = "TestContexts"
context["HPNEW2"] = "TestContexts"
context["HPNEW3"] = "TestContexts"
context["HPNEW4"] = "TestContexts"
context["FOLDER"] = "TestContexts"
context["HPNEW5"] = "TestContexts"
context["VFLDEMO"] = "TestContexts"
context["RSSTEW"] = "TestContexts"
context["HPNEW9"] = "TestContexts"
context["TESTGEN"] = "TestContexts"
context["PLANTIJN2"] = "TestContexts"
context["PLANTIJN"] = "TestContexts"
context["OPL2008"] = "TestContexts"

context["HELP"] = "Systeem"
context["CONTEXTS"] = "Systeem"
context["STUDPORT7"] = "Systeem"

context["VSBB"] = "Steunpunt Buitenlands Beleid"
context["VSBB2"] = "Steunpunt Buitenlands Beleid"
context["VSBBE"] = "Steunpunt Buitenlands Beleid"

context["UCSIA2"] = "UCSIA"
context["UCSIAENG2"] = "UCSIA"
context["FONDSBRUYNS"] = "UCSIA"
context["SUMMERSCHOOL"] = "UCSIA"
context["KIMFONDS"] = "UCSIA"
context["UCSIA_TEST"] = "UCSIA"
context["UCSIAENG_TEST"] = "UCSIA"
context["RETHUNIV"] = "UCSIA"
context["GUESTHOUSE"] = "UCSIA"
context["EYOUTH"] = "UCSIA"

context["KOTWEB"] = "KOTWEB"
context["KOTWEBE"] = "KOTWEB"
context["KOTWEBF"] = "KOTWEB"
context["KOTWEIG"] = "KOTWEB"

context["BBSTUD_START"] = "BB_STUDENTENPORTAAL"
context["BBSTUD_HUISVESTING"] = "BB_STUDENTENPORTAAL"
context["BBSTUD_JOBS"] = "BB_STUDENTENPORTAAL"
context["BBSTUD_CLUBS"] = "BB_STUDENTENPORTAAL"
context["BBSTUD_BEGELEIDING_STUDIEKEUZE"] = "BB_STUDENTENPORTAAL"
context["BBSTUD_BEGELEIDING_FACILITEITEN"] = "BB_STUDENTENPORTAAL"
context["BBSTUD_BEGELEIDING_PSYCHO"] = "BB_STUDENTENPORTAAL"
context["BBSTUD_WEGWIJS_FINANCIERING"] = "BB_STUDENTENPORTAAL"
context["BBSTUD_WEGWIJS_DIPLOMA"] = "BB_STUDENTENPORTAAL"
context["BBSTUD_MIJNSTUDIE_OMBUDSPERSONEN"] = "BB_STUDENTENPORTAAL"
context["UAFACFBDONDADMIN"] = "BB_STUDENTENPORTAAL"
context["UAFACGENONDADMIN"] = "BB_STUDENTENPORTAAL"
context["UAFACLEWONDADMIN"] = "BB_STUDENTENPORTAAL"
context["UAFACPSWONDADMIN"] = "BB_STUDENTENPORTAAL"
context["UAFACRECONDADMIN"] = "BB_STUDENTENPORTAAL"
context["UA_FACTEWONDADMIN"] = "BB_STUDENTENPORTAAL"
context["UAFACTEWONDADMININT"] = "BB_STUDENTENPORTAAL"
context["UAFACWETONDADMIN"] = "BB_STUDENTENPORTAAL"
context["UAINTIOIWONDADMIN"] = "BB_STUDENTENPORTAAL"
context["BBSTUD_EXAMENS_STUDIEVOORTGANG"] = "BB_STUDENTENPORTAAL"

context["OPENING"] = "associatie"
context["STUDINANTWERPEN"] = "associatie"
context["THISISNOTABOOK"] = "associatie"
context["LEERSTOEL"] = "associatie"
context["PWO"] = "associatie"
context["ELANT"] = "associatie"
context["AUHA"] = "associatie"
context["AUHANEW"] = "associatie"
context["AUHANEW2"] = "associatie"
context["WETENSCHAPSCOM"] = "associatie"

context["ECHO"] = "UA - Onderwijs"
context["ONW"] = "UA - Onderwijs"
context["FUSIONSHOW"] = "UA - Onderwijs"
context["ECHONEW"] = "UA - Onderwijs"



